# Generated by Django 5.0 on 2023-12-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_class_course_assignment_mystudent_student_class_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Grade',
        ),
    ]
