# Generated by Django 5.0 on 2023-12-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_rename_course_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystudent',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
