# Generated by Django 5.0 on 2023-12-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_mystudent_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assignment_name',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='file',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_file',
            field=models.FileField(null=True, upload_to='assignment'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_title',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
