# Generated by Django 5.0 on 2023-12-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_announcement_class_class_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='student',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
