# Generated by Django 5.0 on 2023-12-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_announcement_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='student',
        ),
        migrations.AddField(
            model_name='mystudent',
            name='student',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
