# Generated by Django 5.0 on 2023-12-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_accfilter_alter_mystudent_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='accfilter',
            name='Student',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
