# Generated by Django 5.0 on 2024-01-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_accfilter_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystudent',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
