# Generated by Django 5.0 on 2024-01-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_mystudent_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystudent',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
